# Generated by Django 5.1.3 on 2024-11-21 18:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exploitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='OperationCulturale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('type_operation', models.CharField(choices=[('phytosanitaire', 'Phytosanitaire'), ('taille', 'Taille'), ('vendange', 'Vendange')], max_length=50)),
                ('duree', models.DurationField()),
                ('details', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='OperationPhytosanitaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maladie_visee', models.CharField(max_length=255)),
                ('stade_maladie', models.CharField(max_length=255)),
                ('methode_traitement', models.CharField(max_length=255)),
                ('observation', models.TextField(blank=True, null=True)),
                ('operation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='operations.operationculturale')),
            ],
        ),
        migrations.CreateModel(
            name='Salarie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('exploitation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operations.exploitation')),
            ],
        ),
        migrations.AddField(
            model_name='operationculturale',
            name='salarie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operations.salarie'),
        ),
    ]
